name: cloud_portrait
description: Cloud version of Portrait

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.4.2
  firebase_storage: ^10.3.4
  file_picker: ^5.2.2
  exif: ^3.1.2
  flutter_native_image: ^0.0.6+1
  mime: ^1.0.2
  flutter_video_info: ^1.3.1
  video_compress: ^3.1.1
  permission_handler: ^10.2.0
  carousel_slider: ^4.1.1
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/data/assets/logo-google.png